__maestro:
  schema: 2
name: Master_Project_Infarstructure
{%- set zookeeper_share_host = '/root/Master_Project/Master_Project_Infrastructure/docker_share' %}
{%- set zookeeper_share_docker = '/var/docker-share' %}
ships:
  docker-zk-1:
    ip: 192.168.0.106
  docker-zk-2:
    ip: 192.168.0.105
services:
  zookeeper:
    image: 20-maestro-zookeeper:latest 
    instances:
      node1:
        ship: docker-zk-1
        ports: {client: 2181, peer: 2888, leader_election: 3888}
        volumes:
          /tmp: /var/ocker-share
        env:
          ZOOKEEPER_TICKTIME: 2000
          ZOOKEEPER_DATADIR: {{ zookeeper_share_docker }}/v1
          ZOOKEEPER_CLIENTPORT: 2181 
          ZOOKEEPER_SERVER_IDS: 'node1:1,node2:2'
      node2:
        ship: docker-zk-2
        ports: {client: 2181, peer: 2888, leader_election: 3888}
        volumes:
          /var: /tmp 
        env:
          ZOOKEEPER_TICKTIME: 2000
          ZOOKEEPER_DATADIR: {{ zookeeper_share_docker }}/v2
          ZOOKEEPER_CLIENTPORT: 2181 
          ZOOKEEPER_SERVER_IDS: 'node1:1,node2:2'
  kafka:
    image: 20-maestro-kafka:latest
    requires: [ zookeeper ]
    env:
      NODE_NUMBER: 2
    instances:
      kafka1:
        ship: docker-zk-1
        ports: {broker: 9092}
        env:
          BROKER_ID: 1
          NUM_PARTITIONS: 3 
          ZOOKEEPER_SERVER_IDS: 'node1,node2'
      kafka2:
        ship: docker-zk-2
        ports: {broker: 9092}
        env:
          BROKER_ID: 1
          NUM_PARTITIONS: 3 
          ZOOKEEPER_SERVER_IDS: 'node1,node2'
  producer:
    image: 20-maestro-kafka-producer:latest
    requires: [ kafka ]
    env:
      KAFKA_INFO: 192.168.0.106:9092,192.168.0.105:9092
    instances:
      producer1:
        ship: docker-zk-1
  consumer:
    image: 20-maestro-kafka-consumer:latest
    requires: [ kafka ]
    env:
      KAFKA_INFO: 192.168.0.106:2181,192.168.0.105:2181
    instances:
      consumer1:
        ship: docker-zk-1
  spark-slave:
    image: 20-maestro-hadoop:latest
    instances:
      slave1:
        ports: {client: 8088, peer: 9000, ssh: 2122, secondary: 50090}
        ship: docker-zk-2
  spark-master:
    image: 30-maestro-hadoop-master:latest 
    requires: [ spark-slave]
    env:
      SLAVE_IP: 192.168.0.105
    instances:
      master:
        ports: {client: 8088, peer: 9000, ssh: 2122, secondary: 50090}
        ship: docker-zk-1
  hadoop-single:
    image: 30-maestro-hadoop-single:latest
    instances:
      Master: 
        ports: {client: 8088, peer: 9000, ssh: 2122, secondary: 50090, namenode: 50070, jT: 5431, sa: 8035, rt: 8025, rm: 8050, abc: 8031  }
        ship: docker-zk-1
  hadoop-slave:
    image: 20-maestro-hadoop:latest
    instances:
      Slave: 
        ports: {client: 8088, peer: 9000, ssh: 2122, secondary: 50090, namenode: 50070, jT: 5431, sa: 8035, rt: 8025, rm: 8050, abc: 8031  }
        ship: docker-zk-2
