name: Master_Project_Infarstructure
{%- set zookeeper_share_host = '/root/Master_Project/Master_Project_Infrastructure/docker_share' %}
{%- set zookeeper_share_docker = '/var/docker-share' %}
ships:
    docker-zk-1:
        ip: 192.168.0.106
    docker-zk-2:
        ip: 192.168.0.104
services:
    zookeeper:
        image: 20-maestro-zookeeper:latest 
        instances:
            node1:
                ship: docker-zk-1
                ports: {client: 2181, peer: 2888, leader_election: 3888}
                volumes:
                    {{ zookeeper_share_host }}: {{ zookeeper_share_docker }}
                env:
                    ZOOKEEPER_TICKTIME: 2000
                    ZOOKEEPER_DATADIR: {{ zookeeper_share_docker }}/v1
                    ZOOKEEPER_CLIENTPORT: 2181 
                    ZOOKEEPER_SERVER_IDS: 'node1:1,node2:2'
            node2:
                ship: docker-zk-2
                ports: {client: 2181, peer: 2888, leader_election: 3888}
                volumes:
                    {{ zookeeper_share_host }}: {{ zookeeper_share_docker }}
                env:
                    ZOOKEEPER_TICKTIME: 2000
                    ZOOKEEPER_DATADIR: {{ zookeeper_share_docker }}/v2
                    ZOOKEEPER_CLIENTPORT: 2181 
                    ZOOKEEPER_SERVER_IDS: 'node1:1,node2:2'
    kafka:
        image: 20-maestro-kafka:latest
        requires: [ zookeeper ]
        env:
            NODE_NUMBER: 2
        instances:
            kafka1:
                ship: docker-zk-1
                ports: {broker: 9092}
                env:
                    BROKER_ID: 1
                    NUM_PARTITIONS: 3 
                    ZOOKEEPER_SERVER_IDS: 'node1,node2'
            kafka2:
                ship: docker-zk-2
                ports: {broker: 9092}
                env:
                    BROKER_ID: 1
                    NUM_PARTITIONS: 3 
                    ZOOKEEPER_SERVER_IDS: 'node1,node2'
